---
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - nightly
install:
  - pip install pyyaml flake8 flake8-import-order
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pip install coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then pip install sphinx; fi
  - pip install .
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then flake8 .; fi
  - yamllint --strict $(git ls-files '*.yaml' '*.yml')
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then
      coverage run --source=yamllint setup.py test;
    else
      python setup.py test;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then
      python setup.py build_sphinx;
    fi
after_success:
  coveralls
